:PROPERTIES:
:ID:       250DF734-F5BF-443C-984A-F0D0F05C0DBF
:END:
#+title: The Zone Of Interest la perfezione tra immagine visiva e uditiva
#+filetags: :artescienza:cinema:storia:zona di interesse:olocausto:
#+options: author:nil, date:nil, toc:nil, num:5, H:5, html-postamble:nil


* [[https://www.novecento.org/uso-pubblico-della-storia/the-zone-of-interest-la-perfezione-tra-immagine-visiva-e-immaginazione-uditiva-8188/][The zone of interest: la perfezione tra immagine visiva e immaginazione uditiva - Novecento.org]] :website:

[2024-08-11 Sun 23:47]

** Article

Una scena del film “The zone of interest” in uno screenshot tratto dall'autrice.

***** *Abstract*

Il film /The zone of interest/ (2023), diretto da Jonathan Glazer, riesce in un
duplice obiettivo: da una parte rappresenta il punto di vista del Comandante di
Auschwitz, Rudolf Höss, e della sua famiglia con grande perizia storica; e
dall'altra offre una riflessione ben più ampia, in cui gli scenari e i dubbi che
pone dialogano con il nostro tempo in maniera profonda. L'era del turismo di
massa e i viaggi della memoria in gruppo, il tempo del post-testimone e
il-dove-abbiamo-sbagliato ne rappresentano l'orizzonte, focalizzando
l'attenzione sullo /sguardo/ e, dunque, sulla questione stessa del senso che
ricopre (e ha ricoperto) la ricca produzione cinematografica sulla Shoah,
prodotta fino ad oggi. La scelta di uno stile apparentemente nitido, lineare,
geometrico, in realtà rivela la capacità di illuminare una complessità come
pochi altri casi sono riusciti a fare, tanto da catturare letteralmente lo
spettatore fino a trascinarlo al centro esatto della storia narrata, in un gioco
continuo tra ciò che è /mostrato/ e ciò che è solo /udito/, tra ciò che è stato
(passato) e ciò che è (presente). Il film, muovendosi su piani diversi, solleva
considerazioni su Storia, Memoria, Auschwitz, ma anche sul cinema stesso,
sull'etica/estetica della rappresentazione/fruizione, sull'immagine e sui suoi
limiti.

___________________

The movie “The Zone of Interest” (2023), directed by Jonathan Glazer, succeeds
in a twofold objective: on the one hand, it portrays the point of view of the
Auschwitz Commandant, Rudolf Höss, and his family with great historical
expertise; and on the other hand, it offers a much broader reflection, in which
the scenarios and doubts it poses engage in a profound dialogue with our time.
The era of mass tourism and group memory trips, the time of the post-witness and
the where-are-we-wrong represent the horizon, focusing attention on the gaze
and, therefore, on the very question of meaning that covers (and has covered)
the rich film production on the Shoah, produced to date. The choice of an
apparently sharp, linear, geometric style actually reveals the ability to
illuminate a complexity as few others have succeeded in doing, so much so as to
literally capture the spectator to the point of dragging him to the exact centre
of the narrated story, in a continuous game between what is shown and what is
only heard, between what has been (past) and what is (present). The film, moving
on different planes, raises considerations on History, Memory, Auschwitz, but
also on cinema itself, on the ethics/aesthetics of representation/fruition, on
the image and its limits.


***** *L'orizzonte*

Lontano da qualsiasi pedagogia della memoria e distante dalla Shoah come oggetto
culturale, /The zone of interest [[#_ftn1][*[1]*]]/ pone alcuni interrogativi cruciali, in
grado di attraversare questioni che ci riguardano da vicino, rimandando a un
concetto di ‘crisi' della rappresentazione da una parte e della fruizione
memoriale dall'altra. L'operazione sottile di analisi storica e riflessione che
innesca risulta perfetta negli esiti, senza che sia reso /visibile/ il ‘male',
preferendo offrire /apparentemente/ le vicende legate a Rudolf Höss, Comandante
di Auschwitz, e alla sua famiglia [[#_ftn2][[2]]]. Dopo molti film sulla Shoah, /The zone of
interest/ segna, infatti, una novità importante: adotta punti d'osservazione
inediti fino a spingersi verso direzioni inaspettate, senza rischio di
semplificazioni o stereotipi [[#_ftn3][[3]]]. Lo spettatore è coinvolto e stravolto allo
stesso tempo, senza alcun segno di violenza palese sullo schermo. L'empatia che
suscita non è di stampo emotivo, commovente alla /Schindler's list/, ma nemmeno
simile a quella innescata da /Saul Fia/, pur avendo con quest'ultimo alcune
affinità [[#_ftn4][[4]]]. Tra dettagli e composizione rigorosa si insinua la capacità di
guidare l'immaginazione nello /spazio oscuro/ di ciò che lo spettatore guarda e
ascolta: e questo ne fa un'opera originale, quanto necessaria.

La regia -- sorretta da una fotografia e un sonoro altamente significativi [[#_ftn5][[5]]]--
riesce a spiazzare, utilizzando un registro che chiama in causa i sensi di vista
e udito, separando la realtà tra ciò che è /al di là/ e /al di qua/ di un muro
di separazione visiva, che il suono rompe/supera in continuazione: si tratta del
muro di recinzione del campo di concentramento più noto al mondo, Auschwitz. E
se l'immagine si nutre di razionalità geometrica, il suono invece è
l'irrazionalità che entra /in campo/ (in controcampo). La “Zona di interesse”,
così chiamata dalle SS, estesa per 40 km quadrati, comprende il sistema
concentrazionario di Auschwitz, un'area ampia che ingloba la stessa villa degli
Höss, spazio ‘sicuro' entro cui si svolge il racconto. Il Comandante vive
insieme alla moglie e cinque figli, appena fuori dal lager, così vicino da
condividere il muro di cinta del suo giardino con quello del campo stesso. I
luoghi sono ricostruiti fedelmente come i documenti storici e le tracce ancora
evidenti testimoniano [[#_ftn6][[6]]]. Il film nasce non a caso da ricerche pluriennali
condotte negli archivi e con la collaborazione del Museo Nazionale di
Auschwitz-Birkenau [[#_ftn7][[7]]]. La necessità di non inventare, ma semplicemente di
ricreare e mostrare la Storia dalla prospettiva inedita di una /quotidianità/
restituita in modo esatto attraverso le fonti, ricorrendo ad uno stile
impeccabile, segna una frattura nella tradizione della rappresentazione della
Shoah esperita finora al cinema.



***** *Caratteristiche*

Partiamo dalla fine. Si esce dalla sala con la sensazione che si è vissuta
un'esperienza sconvolgente senza che l'orrore sia stato mai mostrato, con
l'interrogativo se quel che si è svolto sotto i nostri occhi riguardi una pagina
di Storia o piuttosto direttamente noi. La sensazione di essere tirati in ballo
non lascia margine a indifferenza o retorica, attualizzando in maniera profonda
un senso di responsabilità; ed è questo il risultato decisivo ottenuto da
Glazer. Come ci riesce? Sicuramente il suo far leva all'immaginario ormai
costituito e condiviso universalmente in tema di Shoah risulta decisivo; alla
fine si rimane basiti, immobili, straniati. Non si vedono sangue, violenza,
spari, morti, terrore, esecuzioni, eppure ci sono. Non si entra ad Auschwitz,
eppure si respira la sua aria fetida, i suoi colori grigi, il suo suono atroce.



Formalmente si rimane su una soglia visiva rappresentata dal perimetro di mura
che delimitano il campo, anche quando la macchina da presa accede un'unica
volta, seguendo il comandante Höss, posizionandosi su un raro primo piano [[#_ftn8][[8]]]
del suo profilo con ripresa dal basso verso l'alto, fino a chiudere sullo sfondo
di un cielo grigio segnato dai fumi delle ciminiere, /senza far vedere nulla,
facendo udire però tutto/. I confini della visione, i limiti dello sguardo sono
superati attraverso i suoni. Come avviene nella realtà in cui talvolta ciò che
si immagina, al di là di ciò che si vede, viene guidato da ciò che si ascolta. A
differenza di /Saul Fia/, in cui ugualmente il fuoricampo uditivo ha una
funzione centrale, la non-visione qui non è frutto di una macchina da presa che
segue stretta il protagonista, lasciando intravedere solo poco del contesto, in
questo caso l'assenza di Auschwitz alla vista è volutamente (quasi) totale, pur
essendo il luogo al centro del film. È un'assenza che vale più di ogni possibile
presenza. Solo la parte finale apre le porte del lager: ci colloca dentro, ma in
un tempo diverso, quello del XXI secolo. E su questo occorrerà soffermarsi più
avanti.

Il regista compie una scelta audace, quella di non /mostrare/ ciò che deve
rimanere /invisibile/, proprio per la sua non-rappresentabilità [[#_ftn9][[9]]], anche
perché tutto è già presente nell'immaginario stratificato universale. Glazer si
concentra su altro. Il risultato è sorprendente, sin dall'incipit, con i tre
lunghi minuti di schermo nero e la sola musica discordante di Mica Levi a
introdurci alla visione. La prospettiva si posiziona immediatamente al di qua
del muro, nel punto in cui non si situa solo la storia narrata, ma può adagiarsi
esattamente ognuno di noi. In una zona di conoscenza e ‘di sicurezza' che ci
appartiene tutti in qualche modo, a differenza di quella /al di là/ che rimane
celata, per il suo essere impossibile da /svelare/ e, dunque, da rappresentare.
In questo vi è il profondo rispetto delle vittime, dei sopravvissuti e dei loro
racconti; un esempio di impegno al tempo della post-memoria. “Come si farà
quando l'ultimo testimone non ci sarà più?” sentiamo spesso chiedere: il regista
inglese /supera/ l'epoca costruita sulle testimonianze. Il punto di vista della
famiglia Höss e del suo capofamiglia/comandante sposta l'attenzione, mostra una
‘normalità' che ci pone in un punto d'osservazione straniante [[#_ftn10][[10]]], ma efficace
per comprendere fino in fondo ciò che è accaduto in Europa ai tempi del
nazifascismo. Colpisce, infatti, che davanti a ciò che non è raffigurabile --
l'orrore, la morte, la disumanizzazione -- l'immaginazione lo renda
onnipresente, grazie al controcampo uditivo. I componenti della famiglia Höss
invece ignorano i suoni terribili provenienti dal lager, ci convivono
allegramente e condividono tutti -- dagli adulti ai bambini, chi più e chi meno
-- una realtà nazista di sterminio che è semplicemente la loro ‘quotidianità',
che il Comandante mette in atto alla perfezione e sua moglie vive come il
paradiso in terra, come il traguardo dei loro sogni di realizzazione [[#_ftn11][[11]]]. Un
orrore che non è solo nei lager, dunque, ma anche al di qua del muro nella
società che ha smesso qualsiasi senso critico [[#_ftn12][[12]]].


Screenshot dell'autrice

***** *La rappresentazione*

Il cielo è terso, non conosce pioggia. I suoni degli uccellini segnano le
stagioni. La natura compone un quadro indifferente, non scevro di una sua
bellezza. Le nuvole scure di fumo, gli sprazzi di fuoco dalle ciminiere segnano
però l'orizzonte in alcune inquadrature, che non mostrano mai in primo piano ciò
che in effetti vogliono indicarci. Gli occhi ci arrivano piano piano, quasi a
mettere a fuoco un'immagine sfocata. Eppure tutto il film è segnato da nitidezza
e luce naturale [[#_ftn13][[13]]]. Perché? Perché si tratta di un processo di messa a fuoco
delle questioni: Auschwitz non è solo il campo di sterminio fisico, è
soprattutto l'emblema di quello che è successo nelle menti delle persone, la
cancellazione di qualsiasi segno di umanità in milioni di Tedeschi, Polacchi,
Italiani, Cechi, Ungheresi, Francesi... Europei. Si tratta, dunque, non di fare
i conti con qualcosa del passato, ma di pensare quello che potrebbe ancora
accadere. Glazer adotta così il punto di osservazione di casa Höss tra 1943 e
1944, entrando in maniera quasi maniacale nella realtà familiare di uno dei
comandanti più famigerati.



La villa appare ben tenuta, nel grande giardino fiorito vi è una piscina
quadrata con scivolo per i bambini. Il Comandante spegne le luci la sera,
accuratamente chiude tutte le porte. Ha uno studio in cui riceve alcune visite
di lavoro [[#_ftn14][[14]]], risponde al telefono e ascolta la radio [[#_ftn15][[15]]]. La camera da letto
dei coniugi vede letti separati. Il figlio più grande, destinato ad assomigliare
di più di tutti al padre [[#_ftn16][[16]]], colleziona e osserva denti d'oro provenienti dal
campo. Dalle molte finestre non si vede quasi mai il /fuori/ (i suoni però
arrivano fino all'interno): la macchina da presa /non guarda quasi mai
attraverso/, non scosta le tendine [[#_ftn17][[17]]]. Solo una volta questo accade, quando la
madre di Hedwig in visita alla famiglia, dopo un arrivo entusiasta e di
soddisfazione nel registrare la ricchezza di cui gode la figlia, svegliata dai
suoni e i rumori provenienti dal campo (lei ancora li sente) si affaccia, e noi
vediamo nel riflesso dei vetri quello che lei sta guardando: le fiamme alte del
crematorio, quando nel 1943 si inceneriva anche la notte a ciclo continuo. La
mattina dopo la madre non sarà più in casa, fuggirà lasciando un biglietto che
verrà bruciato nella stufa dalla figlia notevolmente irritata. L'unico punto del
film in cui Hedwig Höss potrebbe perdere il controllo -- pensare -- e invece
ricomincia la sua vita abituale [[#_ftn18][[18]]], nella sua dimensione di piena occupazione
e soddisfazione. Ordina e amministra inservienti polacchi e prigionieri (purché
non ebrei) per i lavori più umili [[#_ftn19][[19]]], chini con la testa, o per i lavori più
pesanti, come quelli in giardino dove a un certo punto uno di loro sparge ceneri
(umane) sulla terra a mo' di fertilizzante. Rudolf Höss invece esce a cavallo
(amatissimo) per entrare nel campo che è attaccato, fino a quando una promozione
lo costringe a trasferirsi a Berlino, il 1 dicembre 1943, messo a capo di tutti
i comandanti dei campi. La “zona d'interesse” rimane comunque la sua dimensione
totalizzante, tanto da essere ben contento di poterci tornare nel maggio del
1944 per attuare quello che sarà il “suo” sterminio del popolo ebraico
ungherese, l' /Aktion Höss [[#_ftn20][*[20]*]]/. Il film preannuncia questa fase: l'uomo da
Berlino comunica al telefono alla moglie, rimasta per sua ferma volontà ad
Auschwitz, l'azione a cui è chiamato tanto da essere a sua detta “felice da
morire” (87'). La sua missione di sterminio non conosce arresto, come per la
moglie si tratta di rimanere “la regina di Auschwitz” [[#_ftn21][[21]]].




***** *Un'unica ‘zona' di speranza*

Una ricostruzione fedele è quella di Glazer: anche quando si tratta della storia
girata in bianco e nero con utilizzo di camera termica che si inserisce nella
narrazione in maniera singolare e che ha suscitato interpretazioni diverse [[#_ftn22][[22]]].
Si tratta di una storia di resistenza e solidarietà che il regista ha
rintracciato e ha voluto includere, forse unica ‘zona' di speranza nel film.
Come se fosse dentro un negativo, una giovane donna polacca di notte si reca con
la sua bicicletta nei dintorni del lager dove alcuni prigionieri affamati sono
impiegati di giorno, per lasciar loro delle mele, nascoste tra attrezzi e
cespugli. Una sera trova una scatolina di latta con dentro uno spartito che
nell'eseguire al piano, una volta tornata a casa, risuona sulle immagini tornate
a colori della sua modesta abitazione. Quella musica appartiene davvero a un
sopravvissuto, Joseph Wulf, e i sottotitoli riportano silenziosamente alcuni
suoi versi yiddish del 1943, salvati da alcune registrazioni ritrovate. La
musica diviene così elemento magico, poetico, salvifico.



***** *Noi dove siamo?* *Bandita è l'indifferenza*

Il “film udito” -- quel secondo film indicato dal regista insieme al “film
visto” [[#_ftn23][[23]]] -- contribuisce a posizionarci [[#_ftn24][[24]]]. Non esiste confine netto tra un
aldiquà e un aldilà; il muro è incapace di segnarlo. Ma Glazer compie
un'operazione ulteriore che ci riguarda, mettendo in crisi la distanza tra film
e spettatori in sala, fino a trascinarli dentro il gorgo della Storia.

Rivelatrici due inquadrature, entrambe nella parte finale, che ci costringono a
interrogarci e a interrogare ciò che le immagini mostrano. La prima è quella
dello spioncino (94') di una porta della camera a gas che dall'oscurità si apre
verso l'esterno e che noi vediamo schiudersi, ritrovandoci improvvisamente
dentro quel perimetro quadrato: lo sguardo si posiziona esattamente dentro il
mondo attuale, che ci appartiene e che fa dell'esperienza del lager talvolta
un'occasione di gita/viaggio, voyeurismo spesso distratto [[#_ftn25][[25]]]. Una volta aperta
la porta ritroviamo alcuni addetti polacchi che puliscono e mettono in ordine il
luogo, in maniera da prepararlo per i visitatori. Noi siamo così tra quel
/dentro/ la camera a gas (in una posizione scomoda e allo stesso tempo
‘originale') e il /fuori/ che riconosciamo (per conoscenza fisica o ‘virtuale').
Siamo dentro l'inferno, ma ai giorni d'oggi, che è il tempo a noi riservato.



Prima di questa sequenza e subito dopo (93'27”) entra in scena ancora un'ultima
volta Rudolf Höss, che rivediamo nella sua discesa delle scale del palazzo di
Berlino, in uniforme (compresa di cappello calzato poco dopo), verso un buio
totale, quando però in un punto esatto si ferma, si volta e fissa dritto in
camera il suo sguardo, indugiando a figura intera qualche istante; chi o cosa
sta guardando? Perché? Siamo noi ad /essere guardati/ (a chi è rivolto quello
sguardo, se non a noi?), perché l'intera questione ci riguarda: tra imbarazzo e
malessere, lo spettatore si trova così improvvisamente calato in una situazione
obbligatoria di ‘visitatori/abitatori' di un luogo che quell'uomo ha creato e
/da cui nessuno è fuori/ fino in fondo. Höss prosegue poi la sua discesa,
inabissandosi nella zona più ‘nera' della Storia [[#_ftn26][[26]]], ne sentiamo i passi, fino
a quando ricompare l'inquadratura nera dell'inizio e la musica di Mica Levi
risuona di nuovo, sempre più dissonante, ad accompagnarci fino alla fine dei
titoli di coda.

A quel punto il film proietta lo spettatore oltre la Storia: le sequenze lo
trasportano dentro il Museo Nazionale di Auschwitz-Birkenau negli anni Venti del
XXI secolo. Con un balzo attraverso poche scene -- in assenza di parole e musica
-- ecco che ci si ritrova nello spazio espositivo di ciò che resta di un orrore
fin lì volutamente solo udito. Si entra nella dimensione memoriale del
post-testimone, ma anche degli allestimenti museali d'attrazione per un
cineturismo contemporaneo che coinvolge tutti direttamente, dentro una
dimensione che è pubblica e privata allo stesso tempo. Il film diviene
un'interrogazione legittima su ciò che oggi si riesce a /vedere/, sull'esercizio
critico che si compie rispetto alla Shoah [[#_ftn27][[27]]], sulla possibilità di una
fruizione che sia etica nei confronti dei milioni di vittime. La testimonianza
di questi ultimi è anche negli allestimenti di teche enormi di capelli, scarpe,
valigie o lungo i corridoi con i mille volti fotografati e allineati? Quale
senso ha quell'accumulo dettato dagli spazi espositivi oggi meta di frotte di
turisti organizzati? Glazer sembra porre la domanda: “cosa vedono/vediamo
davvero attraverso quei vetri, quei luoghi?”.

Lo spirito del film sembra centrarsi così sullo /sguardo/, sulla visione miope
del presente che ha forti responsabilità per il futuro, dopo aver mostrato lo
sguardo assente dei carnefici e di una società nazista, assuefatta, razzista e
arrivista [[#_ftn28][[28]]]: quindi dopo essersi chiesto “cosa vedevano allora?” si passa --
attraverso una forte linea di continuità rappresentata da Auschwitz -- a “cosa
si vede oggi?”, “quale sguardo si ha su ciò che è accaduto nel cuore d'Europa e
accade ancora oggi?”, ma anche “da quale prospettiva storica e cinematografica
possiamo ripensare/rivedere ciò che è stato?”. La /miopia/ ha saputo (sa)
determinare tragedie, abissi, pericolosa indifferenza. Una “quotidiana
indifferenza” che nella parte finale del film ritroviamo anche nei gesti degli
addetti, che agiscono meccanicamente, per tenere il campo in ordine e pulito,
senza più /guardare/ neanche loro cosa hanno davanti; come se un' /altra/
incapacità visiva si sia sostituita a quella di allora.



***** *Un viaggio nella Memoria*

Una certa insofferenza colpisce lo spettatore: si avverte un disagio davanti a
quella strana, eppure banale, operazione di spolvero dei forni crematori, di
pulizia dei vetri delle teche piene di scarpe o ausili vari, di aspirazione
della polvere lungo il corridoio delle foto di Auschwitz... Perché forse quella
preparazione del luogo è destinata proprio a ciascuno di noi. Chi non è stato o
non andrà in viaggio alla scoperta del male, dell'orrore, della tragedia
dell'umanità? Non basta visitare il campo, commuoversi, tremare al freddo anche
se si è in primavera, se dopo nulla cambia; tutti si è pronti ad acquistare
cartoline e libri, a scattare foto souvenir, ad andare a vedere un film o a
leggere un racconto, ma quanto questo ci interroga su noi stessi? Quanto le
distanze possono annullarsi per far sì che si entri davvero nella comprensione
di eventi storici, rompendo i cliché di percorsi rassicuranti e codificati?
Tutto sembra essere destinato a essere consumato -- anche l'orrore e la morte,
comprese le memorie dei sopravvissuti -- nella dimensione contemporanea di
esperienze che seguono con frenesia strade prestabilite. Glazer si arresta
davanti a questo, offrendo un'importante riflessione sulla capacità/incapacità
di vedere, “inaugura un modo nuovo di creare la memoria” [[#_ftn29][[29]]]: nelle scene
dell'ultima parte del film, cosa attira maggiormente l'attenzione? La teca delle
scarpe o chi ne sta pulendo il vetro, che a sua volta non si sofferma più su ciò
che ha sotto gli occhi? La macchina da presa riprende come fosse un occhio
oggettivo e razionale? Iolo in un punto si avverte, impercettibilmente, il suo
soffermarsi, come se riuscisse a /guardare/ davvero ma soltanto per pochi
istanti; e con essa noi, soprattutto se interpretiamo questo momento come una
soggettiva del nostro punto di vista. Le immagini esprimono così un' /etica/
essenziale nella rappresentazione cinematografica, nella ricostruzione storica e
nel percorso memoriale, restando lontane da qualsiasi tentativo o effetto di
spettacolarizzazione.

--------------

***** *Note:*

[[#_ftnref1][[1]]] Il film (produzione di Stati Uniti, Regno Unito, Polonia) del regista inglese di religione ebraica è uscito in Italia il 22 febbraio 2024. Il titolo rimanda all'opera letteraria omonima (da cui ha tratto iniziale ispirazione, per poi prendere tutt'altra strada) di Martin Amis (Einaudi, Torino 2014). Ha incassato in Italia più di 4,5 milioni di euro (più di 44 milioni di dollari nel mondo) con 679.031 presenze al 20/04/2024. Importante il passaparola a decretare il successo del film in Europa, ancor prima della proclamazione degli Oscar 2024 (Miglior film internazionale e Miglior sonoro). Al Festival di Cannes nel maggio 2023 ha vinto il /Grand prix/. È stato, inoltre, premiato per il Miglior Suono agli /European Film Awards/; ha ricevuto il Premio internazionale della critica /FIPRESCI/.

[[#_ftnref2][[2]]] Cfr. Rudolf Höss, /Comandante ad Auschwitz/, con pref. di Primo Levi e in appendice articolo di A. Moravia, Einaudi, Torino 2014; /Kl Auschwitz seen by the SS: H/ö /ss, Broad, Kremer/, selection, elaboration and notes by Jadwiga Bezwinska, Danuta Czech, Publications of Panstwowe Muzeum w Oswiecimiu, [Oswiecim] 1972. Interessanti tra l'altro in entrambe la riproduzione delle tavole della “Zona di interesse” e relative trasformazioni.

[[#_ftnref3][[3]]] Qui il richiamo è a Primo Levi e al suo monito del 1986, preoccupato che non si avvertisse la differenza tra “le cose com'erano «laggiù» e le cose quali vengono rappresentate dalla immaginazione corrente, alimentata da libri, film e miti approssimativi. Essa, fatalmente, slitta verso la semplificazione e lo stereotipo; vorrei porre qui un argine contro questa deriva” ( /Opere/  /complete/, II, Einaudi, Torino 2017, pp. 1246-7).

[[#_ftnref4][[4]]] La critica ha parlato in più casi dei due film come l'uno il controcampo dell'altro. Sicuramente l'utilizzo del campo uditivo rimanda a /Saul fia/ di László Nemes (2015). Per un'analisi del rapporto tra immagine e suono cfr M. Guerra,  /Il limite dello sguardo. Oltre i confini delle immagini/, Raffaello Cortina editore, Milano 2020. Per un approfondimento su /Saul fia/, sempre su questa rivista si veda D. Garofalo, [[https://www.novecento.org/scolpire-il-tempo-cinema-e-storia-cinema-e-storia/la-shoah-nel-cinema-est-europeo-contemporaneo-8015/][/La Shoah nel cinema est-europeo contemporaneo/]], in “Novecento.org”, n.21, giugno 2024.

[[#_ftnref5][[5]]] Łukasz Żal è il direttore polacco della fotografia; la ricerca sonora, frutto di ricerche sofisticate per ricostruire con la massima fedeltà i ‘rumori' provenienti dal lager, è di Johnnie Burn. Mica Levi ha composto le musiche e a Cannes ha dichiarato: “Per tutto il film la musica ti porta in un posto al di sotto o oltre quello che stai vedendo, quasi un luogo di nessuno, al di là della comprensione logica” (cfr. l'intervista di Sion O'Hagan, /Jonathan Glazer on his Holocaust film The Zone of Interest: ‘This is not about the past, it's about now'/, su “The Guardian”, 10/12/2023).

[[#_ftnref6][[6]]] Dal punto di vista cronologico l'opera per esigenze narratologiche presenta alcuni slittamenti temporali: come il compleanno del Comandante, festeggiato all'inizio del film, in estate, mentre era nato il 25 novembre 1901; o il fatto che la famiglia Höss sia al completo, con l'ultima nata di pochi mesi; in realtà l'ultimogenita era nata il 7 novembre 1943, e questo non coincide con la cornice temporale del film che si svolge tra inizio 1943 e aprile 1944.

[[#_ftnref7][[7]]] Glazer ha girato ad Auschwitz, tra i pochi ad essere autorizzato. La villa Höss è dal 1946 abitata da civili: il regista vi è entrato e per il film ha voluto riprodurla esattamente a poca distanza. Sul campo cfr. S. Steinbacher, /Auschwitz/, Einaudi, Torino 2005.

[[#_ftnref8][[8]]] Il film predilige inquadrature medie e larghe, evitando indugi sui primi piani, che sono pressoché assenti.

[[#_ftnref9][[9]]] Interessante a questo proposito su “Huffpost” il 29 febbraio 2024 in /La zona d'interesse. Il tempo in cui la memoria della Shoah diventa immaginazione/ W. Goldkorn sottolinea: “Quando diciamo “indicibile”, significa che va detto. E quando parliamo di “inimmaginabile” è perché bisogna immaginarlo”. Inoltre cfr. “Cahiers du Cinema”, /Filmer l'infilmable. De Shoah à La Zone d'intérêt/ , n. 808 monografico, aprile 2024.

[[#_ftnref10][[10]]] Quello che Elena Pirazzoli indica come “spaesamento”, in E. Pirazzoli, /“La zona d'interesse”, ovvero l'ordine sovvertito delle cose/, in /“ilmanifesto-inrete”, 29/02/2024/ [[https://www.ilmanifestoinrete.it/2024/02/29/la-zona-dinteresse-ovvero-lordine-sovvertito-delle-cose/]]

[[#_ftnref11][[11]]] Solo alcune spie mostrano un'inquietudine che aleggia: i giochi del figlio più piccolo tra ombre e soldatini, il sonnambulismo della figlia, la fuga della nonna, il pianto disperato e ricorrente dell'infante, le bevute di alcool della tata in mansarda, il cane di casa che si aggira in continuazione come agitato da ciò che annusa, fino ai conati di vomito lungo la scala del palazzo di Berlino del Comandante.

[[#_ftnref12][[12]]] Cfr. H. Arendt, /La banalità del male. Eichmann a Gerusalemme/, Feltrinelli, Milano 2023 (nuova ed.).

[[#_ftnref13][[13]]] Tutto il film è girato con uso di luce naturale: per le scene in notturna viene adoperata la camera termica, pur di non ricorrere a luci artificiali. Il risultato è quello di immagini in bianco e nero, laddove il ‘calore' dei corpi illumina la notte.

[[#_ftnref14][[14]]] In una sequenza alcuni funzionari della ditta J.A. Topf und Söhne incontrano il Comandante per illustrare l'efficientamento del campo che permette il completo avvio del sistema perfetto di “fabbricazione della morte”. Nelle scene ne è mostrato il progetto e ne è illustrato il risultato. La ditta in questione aveva ottenuto il brevetto “Per un forno di cremazione continua di corpi [umani]”, e nel 1943 si adopererò a sfruttare il calore dei forni crematori nelle camere a gas adiacenti, per lo scioglimento immediato dello Zytlon B. Per documenti e rifermenti alla ditta in questione cfr *.* Jean-Claude Pressac, /Auschwitz: Technique and operation of the gas chamber/, The Beate Klarsfeld Foundation 1989 e il sito [[https://www.topfundsoehne.de/ts/en/site/index.html]].

[[#_ftnref15][[15]]] Ad un certo punto alla radio si dà la notizia di una vittoria calcistica dell'Italia sulla Spagna allo stadio di San Siro, con il risultato di 4 a 0: quell'evento è avvenuto il 19 aprile 1942. Il film in realtà è ambientato nel 1943, e la scena in questione come un altro riferimento positivo all'Italia fa capire che si è comunque prima dell'8 settembre.

[[#_ftnref16][[16]]] Tra le fonti interessante la deposizione di Janina Szczurek, la sarta polacca in casa Höss, riportata in /Kl Auschwitz seen by the SS: H/ö /ss, Broad, Kremer/, selection, elaboration and notes by Jadwiga Bezwinska, Danuta Czech, Publications of Panstwowe Muzeum w Oswiecimiu, [Oswiecim] 1972, pp. 293-294 (ora disponibile in italiano [[https://www.irsifar.it/wp-content/uploads/2024/04/janina-THE-ZONE.pdf]]). Nel film si capisce che il lavoro del padre ha inquinato il gioco dei figli, quando il più grande rinchiude il fratello nella serra e poi lo prende in giro, emettendo il sibilo del gas (83').

[[#_ftnref17][[17]]] La tecnica usata di telecamere statiche è singolare: sono state appostate e nascoste in diversi punti senza la presenza dell'operatore. In questo modo gli attori hanno recitato con maggiore libertà.

[[#_ftnref18][[18]]] Su questo Glazer ha sottolineato che l'assenza di riflessione è proprio in quell'essere continuamente indaffarata di Hedwig. Diverso il caso del marito che tra silenzi e sguardi lunghi è alle prese con la /complessità del male/ (espressione coniata da Damiano Garofalo), di cui diviene ideatore e esecutore.

[[#_ftnref19][[19]]] Come pulire dal sangue gli stivali del Comandante al ritorno dal campo.

[[#_ftnref20][[20]]] /Aktion Höss/ è il nome assegnato dai nazisti nel 1944 alle operazioni di sterminio degli ebrei ungheresi ad Auschwitz--Birkenau, tra maggio e luglio del 1944, che costò la vita a circa 400.000 persone. Cfr. D. Czech, /Kalendarium Gli avvenimenti nel campo di concentramento di Auschwitz-Birkenau Gennaio -- Giugno 1944/, versione italiana a cura di ANED, [[http://www.associazioni.milano.it/aned/kalendarium/1944_1.pdf][www.associazioni.milano.it/aned/kalendarium/1944_1.pdf]]

[[#_ftnref21][[21]]] “Rudi mi chiama la Regina di Auschwitz” rivela alla madre, ridendo con soddisfazione (43' 21”). Una “regina” che sa essere spietata, disumana: alla sua cameriera poco dopo dice per rimproverarla duramente: “Potrei chiedere a mio marito di spargere le tue ceneri sui campi di Babice”. R. Höss scrive nella sua memoria: “In verità, la mia famiglia stava bene ad Auschwitz. Ogni desiderio di mia moglie o dei bambini era esaudito. I bambini vivevano liberi e all'aperto, e mia moglie aveva il lusso di un giardino fiorito che era un vero paradiso” (in /Comandante ad Auschwitz/, cit., pp. 138-139). Sul punto di vista dei carnefici interessante /Michael Wildt, “Das ist unser Lebensraum“. Alltag neben dem Unvorstellbaren (Zone of Interest), in Zeitgeschichte-online, 12 März 2024/. In /Novecento.org/ di E. Perra, /[[https://www.novecento.org/scolpire-il-tempo-cinema-e-storia-cinema-e-storia/conspiracy-soluzione-finale-e-la-conferenza-di-wannsee-tra-verita-storica-e-invenzione-cinematografica-8021/][“Conspiracy -- Soluzione Finale” e la Conferenza di Wannsee tra verità storica e invenzione cinematografica]]/, in “Novecento.org”, n.21, giugno 2024.

[[#_ftnref22][[22]]] Qui la musica di Mica Levi risulta intermittente, tormentata, dall'effetto disturbante. La sequenza enigmatica si inserisce dopo la scena in casa Höss in cui i bambini si addormentano con le fiabe dei Fratelli Grimm, lette dal padre. Inizialmente sembra quasi uno stato onirico. Glazer ha chiarito che la scelta è dettata dall'incontro di una donna di 90 anni di nome Alexandria, che aveva lavorato per la resistenza polacca quando aveva solo 12 anni e le scene con camera termica riproducono la sua storia. La bicicletta, la casa e il vestito utilizzati sono realmente quelli originali. Cfr. intervista di Sion O'Hagan in O'Hagan, 2023.

[[#_ftnref23][[23]]] O'Hagan, 2023

[[#_ftnref24][[24]]] Cfr. R. Escobar, /Controcampo sul lager della nostra disumanità/, in “Il Sole-24ore”, 25/02/2024.

[[#_ftnref25][[25]]] Emblematico /Austerlitz/ di Sergei Loznitsa del 2016.

[[#_ftnref26][[26]]] A preannunciare forse anche il suo stesso destino: sarà giustiziato per impiccagione davanti al suo ufficio ad Auschwitz il 16 aprile 1947, dopo essere stato catturato dagli Alleati e processato dalla Corte Suprema di Varsavia, riconosciuto colpevole di crimini contro l'umanità.

[[#_ftnref27][[27]]] Per una riflessione sullo sguardo, oltre a Michele Guerra, /op. cit/., si rimanda anche a M. Cousins,  /Storia dello sguardo/, Il Saggiatore, Milano 2018.

[[#_ftnref28][[28]]] Questo è evidente dai dialoghi in casa tra Hedwig e le sue amiche (si parla del Canada, dei prodotti che arrivano nelle case, sottratti alle vittime, si parla di ebrei senza nominarli, indicandoli industriosi, tanto da nascondere i diamanti in un dentifricio), o dalla conversazione in giardino con la madre, la quale commenta con naturale freddezza che al di là di quel muro deve essere passata probabilmente anche la signora di cui era stata cameriera, e con rammarico aggiunge di non essere riuscita ad accaparrarsi le sue belle tende, quando era stata deportata.

[[#_ftnref29][[29]]] Goldkorn, 2024 /./



:artescienza:cinema:storia:zona di interesse:olocausto:
