:PROPERTIES:
:ID:       80CE5855-43B4-4303-B608-C5117F3F7C8D
:END:
#+title: La realtà diminuita di Apple Vision
#+filetags: :realtà-virtuale:simulazioni:Platone:consciousness:neowearable:cyberpunk:AppleVision:spatialcomputing:simulazionimpure:digitalismo:iperrealtà:

#+options: author:nil, date:nil, toc:nil, num:5, H:5, html-postamble:nil

#+begin_quote

Non si può non scomodare Platone quando si parla di realtà virtuale. Non tanto per l’autorevolezza del lascito filosofico, quanto per l’inesauribile
ricchezza interpretativa delle allegorie tramandate. Se ad esempio si prendono i prigionieri della celebre caverna descritta nella Repubblica e al posto
delle catene che li tengono imprigionati davanti alle ombre li si dota di visori per una realtà alternativa, ecco che l’antica critica al mondo dell’opinione
acquista nuovo senso e diventa una denuncia verso le recenti apparecchiature digitali. Nonostante il paragone fra la catabasi platonica e l’uso acritico
di dispositivi come l’Apple Vision sia stato proposto in diverse varianti, soprattutto in seno a questa veste polisemica, tuttavia non sempre è facile
giungere a conclusioni capaci di rimanere fedeli a realtà così lontane fra loro. 

Il visore per la realtà ibrida di casa Apple è un computer in miniatura dotato di telecamere e di uno schermo ad alta risoluzione che richiede di essere
indossato sul viso da un utente come fossero degli occhiali; gli apparecchi di registrazione catturano ciò che l’utente ha attualmente davanti a sé e lo
“mandano in onda” sui monitor, integrando immagini reali con grafiche digitali sovraimpresse. Diversamente dai prigionieri dell’allegoria, il moderno
recluso non nasce con le catene ai polsi ma sceglie consapevolmente di indossarle dopo aver fatto almeno un’esperienza della realtà esterna (della
quale fa parte anche il visore stesso). L’elemento mancante è quello della credenza: indossare il visore non implica una conversione automatica delle
proprie opinioni sul mondo e non ci illude che i surrogati digitali somministrati dagli schermi siano la realtà stessa. In un certo senso, il fascino per i
wearable device – protesi esterne di un neo-transumanesimo – trova le sue ragioni proprio nell’inversione del modello pedagogico di Platone, cioè
nella fuga verso gradi di realtà “inferiori”, avvicinando i dispositivi più al mondo dell’arte che non a quello della neuropsicologia. 

Dove rintracciare allora le cause del rinnovato interesse per le simulazioni dopo l’uscita di Apple Vision? Casey Neistat, noto youtuber americano
specializzato in lifestyle e tecnologia, al lancio del prodotto riporta la sua esperienza e dice: «dopo un paio d’ore di utilizzo il mio cervello si è
dimenticato che stava usufruendo di una serie di telecamere e schermi e ha iniziato a considerare quelle immagini come la realtà». L’entusiasmo
trasmesso dal vlog sembra rivolgersi paradossalmente ad una caratteristica che ci si aspetterebbe passi in secondo piano ma che in ultima istanza è
il punto di forza del visore: la registrazione digitale del campo visivo. Registrazione che niente ha a che fare con la credenza poiché limitata alla
sollecitazione delle sensazioni visive. Effettivamente la cosiddetta tecnologia dello spatial computing – interazioni digitali uomo/macchina mediante
l’utilizzo di sensori e schermi progettati per dare l’illusione che avvengano nel mondo reale – è proprio la carta sulla quale Apple ha puntato tutto. Non
tanto, quindi, la qualità o l’autenticità dei contenuti virtuali trasmessi ma l’evoluzione della fruizione e dell’interazione. Un perfezionamento informatico,
questo, che secondo le caratteristiche dei prodotti digitali designate da Lev Manovich non può ancora mutare radicalmente il medium ma
semplicemente presentarlo sotto una nuova veste; essendo ancora dotato di uno schermo, il rapporto spaziale che intratteniamo con esso ricalca più
la tradizione della rappresentazione che non quella della simulazione: «in sostanza, la realtà virtuale continua la tradizione d’immobilità imposta dallo
schermo legando il corpo a una macchina […] Se nella tradizione simulatoria lo spettatore esiste in un unico spazio coerente […] nella tradizione
rappresentativa lo spettatore assume una doppia identità, esiste simultaneamente nello spazio fisico e nello spazio rappresentativo» [1]. 

Ogni qualvolta si parla di mondi simulati entra in vigore una specie di riduzionismo empirista, per il quale basterebbe prendere un cervello e collegarlo
ad una macchina capace di somministrare segnali elettrici e illuderlo così dell’esistenza di una realtà digitale surrogata. Senza tener conto né delle
strutture cognitive pregresse né dell’ambiente in cui tale soggetto si sviluppa. Nel caso si prendesse il personaggio di un videogioco, cioè un ammasso
di bit interpretati da un processore e da una scheda video, la domanda sul fatto se sia cosciente o no del mondo in cui vive o se dubiti sulla presenza
di una realtà di maggior grado è paradossalmente meno problematica rispetto a quelle che David Chalmers ha chiamato simulazioni impure. 

Ciò che noi comunemente chiamiamo realtà è considerabile, nella teoria della simulazione, una simulazione pura, poiché partecipiamo ad essa senza
apparente soluzione di continuità e, nonostante la tradizione metafisica si sia interrogata a lungo sul problema dei mondi esterni, diamo per scontato
che tale realtà sia l’unica realtà; stessa cosa se ci mettiamo nella prospettiva di un personaggio in un’opera digitale. Le simulazioni impure, invece,
sono situazioni come la caverna di Platone, lo scenario dei cervelli in vasca di Hilary Putnam, il Matrix di cui è succube Neo nel film omonimo e,
perché no, ad un livello embrionale anche gli occhiali di Apple. 

Tutti questi esempi condividono la medesima caratteristica: l’interazione fra un mondo fisico e un mondo virtuale/digitale rappresentato. Aspetto
cardine delle simulazioni pure è che l’”utente” non può rendersi conto della loro possibile illusorietà, essendo loro stessi e i loro assetti cognitivi parte
di quella realtà (come non tributare a Cartesio e al suo genio maligno gli albori di queste riflessioni). Nelle simulazioni impure, invece, per quanto
eccellano a somministrare dati empirici verosimili presentano forti carenze epistemologiche, soprattutto in relazione allo sviluppo di una credenza sul
mondo. Possono sicuramente generare un’illusione fittizia attraverso l’esercizio continuativo dell’abitudine, come nel caso di Neistat, ma l’effetto
rimane aleatorio e temporaneo. David Chalmers propone di considerare le realtà virtuali per quello che sono: settori della realtà contenenti oggetti
digitali, cioè rappresentazioni numeriche calcolate, interpretate e restituite come output sensoriali. «La mia visione è una sorta di realismo virtuale […]
Il realismo virtuale è la tesi che la realtà virtuale sia una realtà genuina, con l’enfasi sul fatto che gli oggetti virtuali non siano mere illusioni. […]
Certamente, se siamo in una simulazione, gli alberi, le macchine e Beyoncé non sono esattamente come pensiamo che siano. Nel profondo, ci sono
alcune differenze. Pensiamo che gli alberi, le macchine e i corpi umani siano in definitiva composti da particelle fondamentali come gli atomi e i quark;
invece sono fatti di bit» [3]. La suggestione di questa reality+, oltre ad essere largamente inclusiva, conferisce maggiore concretezza ad entità che il
senso comune, considerando appartenenti a gradi di realtà alternativi, rischia di far cadere ancora una volta nel ginepraio del dualismo ontologico. 

Tuttavia, una volta ricondotto il realismo virtuale a questo digitalismo virtuale (altro termine introdotto da Chalmers), e assodato il fatto che i nuovi
dispositivi di realtà aumentata non possono essere simulazioni pure, la conseguenza primaria scaturente è che i visori come quelli di Apple possono
ambire soltanto a rappresentare nuove forme di personal computer. Nello specifico, potremmo chiamarli first person computers – computer in prima
persona, dove il normale accesso ai contenuti digitali avviene mediante l’introduzione del movimento spaziale dell’utente invece che mediante mouse,
tastiera e monitor. Dalla mano si passa quindi all’interezza del corpo. Ad uno sguardo più attento, infatti, non esiste una differenza sostanziale fra un
MacBook e il nuovo l’Apple Vision, se non nella forma e nella fruizione, così come non ci fu differenza sostanziale fra il primo iPhone e i precedenti
dispositivi informatici. La rinnovata attrazione che proviamo dopo il lancio del prodotto e quella che proveremo con l’avvento delle sue versioni future è
legata maggiormente al cambio del nostro stile di vita, a quell’innervazione tecnica che per Walter Benjamin era il segno della modernità; una
modernità che struttura le sue fondamenta tecnologiche proprio al fine di nascondere lo iato che divide le rappresentazioni dai loro oggetti. Se proprio
si vogliono chiamare simulazioni gli ultimi ritrovati della tecnica, il senso più coerente è forse quello impiegato da Baudrillard in Simulacres et
simulation: artifici in cui non soltanto vi è una duplicazione di oggetti naturali (come nel cinema), ma in cui le copie perdono il riferimento verso i propri
originali fino a generare realtà fittizie autoreferenziali (iper-realtà) che fagocitano il reale e lo restituiscono modificato, spacciandolo comunque per un
prodotto naturale di livello superiore [4]. In un certo senso il digitalismo virtuale, pregno della tecnologia dello spatial computing, si innerva al tal punto
da passare sotto la veste della realtà alternativa, quando invece rimane soltanto un segno che rimanda a se stesso: fenomeno tipico della società del
capitalismo avanzato. Nel gergo platonico: un’ombra che rimanda a un’altra ombra.

[1] Lev Manovich, Il linguaggio dei nuovi media, Edizioni Olvares, 2002, pp. 149-151.
[2] David J. Chalmers, Reality+,W. W. Norton & Company, 2022, pp. 10. 
[3] Cfr. Jean Baudrillard, Simulacres et simulation, Galilée, 1981.

CREDITI FOTO: EPA/ADAM DAVIS
#+end_quote



