:PROPERTIES:
:ID:       4374EF65-BFA5-44CA-B713-9782436DF7AE
:END:
#+title: Il postmoderno
#+options: author:nil, date:nil, toc:nil, num:5, H:5, html-postamble:nil

** Zu den Bedingungen der Postmoderne



Leider liegt für dieses Bild keine Bildbeschreibung vor
Postmoderne Architektur: Appartementhäuser Walden 7 von Ricardo Bofill in Barcelona © dpa picture alliance / John Walton
Von Walter van Rossum | 05.02.2014


Im Jahr 1979 veröffentlichte der französische Philosoph Jean-François Lyotard ein Buch, dem eine verblüffende Karriere bevorstand: Das
postmoderne Wissen. In diesem Buch beschrieb er das Ende der großen Erzählungen von Aufklärung und Idealismus.
Aus dem PodcastZeitreisen
Lyotards Überlegungen sind nicht nur zu einer Art Bibel der Kulturwissenschaften geworden, sondern prägten auch Architektur, Literatur, Kunst oder
Design. Walter van Rossum stellt die Thesen des Buches vor, erinnert an die frühe Rezeption dieses Textes und fragt nach den Auswirkungen des
postmodernen Denkens auf den Wissenschaftsbetrieb von heute.

[[file:~/Downloads/zu-den-bedingungen-der-postmoderne-pdf-100.pdf][Manuskript]]
[[file:~/Downloads/100_geburtstag_von_jean_francois_lyotard_ist_die_postmoderne_drk_20240804_1315_83692653.mp3][Audiodatei]]
