:PROPERTIES:
:ID:       1FC9E9E0-E4BF-456F-A769-3B89EB62C083
:END:
#+title: Cancel Culture
#+filetags: :articoli:storia:cultura:politica:cancel-culture:Cristoforo-Colombo:democrazia:Occidente:schiavismo:

#+options: author:nil, date:nil, toc:nil, num:5, H:5, html-postamble:nil


** Article

Giancarlo Bosetti

Le parole “ /cancel culture/” sono diventate come un telecomando magico,
collegato al cervello collettivo, che scatena indignazione e rabbia all'istante,
senza sottilizzare nel merito della questione. La cultura dei cancellatori va
tenuta sotto osservazione perché, naturalmente, *chi vuol cancellare ferisce la
libertà di espressione*, che questa riguardi monumenti o libri, statue del
famoso negriero Robert Milligan o vecchi autori, magari classici, entrati in
conflitto, ex post e a loro insaputa, con gli standard della cultura liberale
contemporanea. Ma le teste rocciose fioriscono anche tra quelli che premono
continuamente il grilletto con quelle due parole. In America ma anche qui da
noi.

Esempi? Un articolo on line di una testata locale a San Francisco racconta la
riapertura della Disneyland californiana e recensisce una nuova installazione
dedicata a Biancaneve. Alla fine del pezzo, si nota che il bacio d'amore del
principe che risveglia la donna come morta sotto l'effetto del veleno oggi
stupisce e poteva essere risolta meglio, come avviene in realtà nel film di
Disney. Fox-news non bada a sfumature e fa esplodere il caso, per capirci, come
se i Democratici avessero proposto al Congresso di mettere fuori legge
Biancaneve. Il che ovviamente non è. Il caso rimbalza in Italia e in rete
fioriscono i paragoni con i roghi nazisti dei libri. *Roghi nazisti, niente di
meno.* Altro esempio: un articolo del Guardian specula sulla storia della torta
di mele americana sostenendo che la ricetta non è americana, ma di origine
indiana. Discutibile come la storia del curry, se sia invenzione indiana o
inglese con spezie indiane riportate a casa dai soldati britannici. O se
l'hummus sia nato tra i libanesi o tra gli israeliani. Niente da farci guerre,
temi persino divertenti. Ma un tabloid di destra rilancia il pezzo sostenendo
che la “ /American apple pie/ adesso è cancellata”. Ha premuto il telecomando e
la storia rimbalza in Italia, Salvini e Meloni twittano: “Siamo alla follia”.
Come se qualcuno volesse proibire la torta di mele.

Sul senso di tutto questo interviene, davvero controcorrente, l'ultimo numero
sorprendente e squillante della rivista trimestrale, diretta da Laura Paoletti,
«Paradoxa», a cura di Gianfranco Pasquino. È dedicato all'«uso e all'abuso»
della /cancel culture/. Sì perché *c'è un abuso ma dunque anche un uso di questa
«etichetta denigratoria»*, che viene impiegata per denunciare una dittatura
orwelliana, un giorno sì e un giorno no, ogni volta che una voce protesta contro
razzismo, soprusi e discriminazioni, nel presente e nel passato. Dunque anche
chi preme il telecomando, o il «fischietto per sguinzagliare i cani» -- cito da
«Paradoxa» e dai saggi di Belardinelli, Boni, Bordignon, Cento, Giglietto,
Mariani e Nedelmann -- vuole chiudere la bocca a qualcuno.

Sembra per esempio che non si possa più discutere su Cristoforo Colombo e sulla
sua idea (questo convintamente pensava) che gli indios fossero esseri inferiori
dunque meritevoli per natura di diventare schiavi. E perché mai non si dovrebbe?
Per non offendere gli italiani? Perché il monumento e il Columbus day hanno
finito per rappresentarli e per risarcirli del razzismo e dei linciaggi subiti
un secolo fa? O per non offendere l'Occidente? *La storia è sempre aperta a un
riesame dei fatti in profondità.* Colombo e i suoi metodi furono discussi già
allora, non è solo senno di poi, e furono condannati e corretti, se pur con
ritardo dallo stesso imperatore Carlo V, cui pure l'oro rimediato da lui e da
Cortès faceva comodo. Ci fu chi lo spinse a farlo: Bartolomé de Las Casas,
combattendo quella che oggi definiremmo una lunga battaglia politica e giuridica
per i diritti degli indios. Aveva dei nemici, che somigliano non poco a quelli
che oggi aizzano i cani contro la /cancel culture./

Discutere Colombo è un suicidio dell'Occidente? È una prova di viltà?
Nient'affatto, al contrario, se troviamo delle ragioni per sventolare la
bandiera dell'Occidente possiamo essere fieri delle pagine in cui *la
riflessione critica e la ricerca storica hanno vinto sulla prepotenza, sulla
censura e sulla retorica*. E vergognarsi di qualche altra pagina. Proprio come
la Chiesa cattolica, per fare un altro esempio, può essere fiera della critica e
delle scuse avanzate per il processo a Galileo nel 2000 da Papa Wojtyla e
vergognarsi del rifiuto di farlo lungo quattro secoli. Sarebbe salutare vedere
tutte le culture cimentarsi in una gara critica sul proprio passato, una
attività che fortifica chi la pratica e testimonia di un regime di libertà.

Vero dunque che i cancellatori presentano rischi di superficialità, estremismo,
avventatezza, ma vero anche che l'ondata di piena sembra aver toccato il massimo
e ora discendere. E bisogna riconoscere -- come fa Pasquino -- che la /cancel
culture/ *ci obbliga a riflettere sulla democrazia* e sui modi in cui si
svolgono i nostri dibattiti pubblici (a proposito come mai non se ne fanno più,
di grandi, da trent'anni?) e gruppi che esercitano con forza la critica fanno
parte a pieno titolo di una democrazia ideale.

Essa ha dunque una funzione essenziale per quanto sgradevole e disturbante, come
il «Progetto 1619» del New York Times, (intitolato dall'anno del primo sbarco di
schiavi in Virginia) tanto esecrato da chi non è disposto a riconoscere che la
schiavitù non fu un incidente di percorso, ma un fatto che ha sistematicamente
caratterizzato la storia della nazione americana, della sua economia, del suo
capitalismo, del suo percorso costituzionale. Alcune tesi dei saggi raccolti in
un libro sono state discusse ed emendate. Ed è molto difficile negare che le
conseguenze di questa storia ancora dividono profondamente gli Stati Uniti.



:articoli:storia:cultura:politica:cancel-culture:Cristoforo-Colombo:democrazia:Occidente:schiavismo:

