* [[https://mail.google.com/mail/mu/mp/888/#cv/In%20arrivo/19143729e8b12eb5][Gmail]]
[2024-08-12 Mon 08:53]
* [[https://hledger.org/basics.html][Tutorial: hledger basics - hledger]]
[2024-08-12 Mon 09:21]
* [[https://m.youtube.com/watch?v=EWjoblLoD3k][Ledger CLI, Personal finance in the command line by Edwin Espinoza - YouTube]]
[2024-08-12 Mon 09:16]
* TODO Prova di sync con beorg 
- Note taken on [2024-08-13 Tue 09:18] \\
  Una nota
[2024-08-13 Tue 09:17]
* 
[2024-08-22 Gio 08:48]

  Zu den Bedingungen der Postmoderne
  
  Leider liegt für dieses Bild keine Bildbeschreibung vor 
  Postmoderne Architektur: Appartementhäuser Walden 7 von Ricardo Bofill in Barcelona © dpa picture alliance / John Walton
  Von Walter van Rossum | 05.02.2014
  
  * SVG ImageLink kopieren/teilen 
  
   Der Link wurde in die Zwischenablage kopiert.
  
  * SVG ImageEmail
  
  Im Jahr 1979 veröffentlichte der französische Philosoph Jean-François Lyotard ein Buch, dem eine verblüffende Karriere bevorstand: Das
  postmoderne Wissen. In diesem Buch beschrieb er das Ende der großen Erzählungen von Aufklärung und Idealismus.
  Aus dem PodcastZeitreisen
  Lyotards Überlegungen sind nicht nur zu einer Art Bibel der Kulturwissenschaften geworden, sondern prägten auch Architektur, Literatur, Kunst oder
  Design. Walter van Rossum stellt die Thesen des Buches vor, erinnert an die frühe Rezeption dieses Textes und fragt nach den Auswirkungen des
  postmodernen Denkens auf den Wissenschaftsbetrieb von heute.
